### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by rehanmumtaz** [Chainski/MAC-Generator#2]
Hello Sir, 

I am trying to get this script but I am unable to make it, below are the errors when I run it in windows as well as parrot os

![2024-01-16 09_40_23-MAC-Generator-main](https://github.com/Chainski/MAC-Generator/assets/40135721/afc8c092-d247-413f-ba88-d26b12d44bd5)

In parrot os, after running the script , few new files appear in the folder but script doesnt run

![2024-01-16 09_47_23-parrot - VMware Workstation 17 Player (Non-commercial use only)](https://github.com/Chainski/MAC-Generator/assets/40135721/f6d1e7ee-e93b-4b39-b09e-69ba004a9b24)

**Comment by rehanmumtaz** [comment]
![Uploading 2024-01-16 09_49_02-parrot - VMware Workstation 17 Player (Non-commercial use only).png…]()

**Comment by rehanmumtaz** [comment]
![2024-01-16 09_49_02-parrot - VMware Workstation 17 Player (Non-commercial use only)](https://github.com/Chainski/MAC-Generator/assets/40135721/df5f11ac-a041-4a13-8083-7e3a235c0148)

**Comment by chainski** [comment]
> Hello Sir,
> 
> I am trying to get this script but I am unable to make it, below are the errors when I run it in windows as well as parrot os
> 
> ![2024-01-16 09_40_23-MAC-Generator-main](https://private-user-images.githubusercontent.com/40135721/296934645-afc8c092-d247-413f-ba88-d26b12d44bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDIzOTIsIm5iZiI6MTcxMTI0MjA5MiwicGF0aCI6Ii80MDEzNTcyMS8yOTY5MzQ2NDUtYWZjOGMwOTItZDI0Ny00MTNmLWJhODgtZDI2YjEyZDQ0YmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAxMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDk3NDQ1ZGI4MTlmM2M5YzA5MTg2ODZlZjJmOTQxNzA2ZjMzYTQ3NzcxZTdkNmQ2NmNlNjE5MGFiZTY3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iJo4OiyzLb6sCXrGFir4ms04tnBEKvuoGrUeYFbJ4Qw)
> 
> In parrot os, after running the script , few new files appear in the folder but script doesnt run
> 
> ![2024-01-16 09_47_23-parrot - VMware Workstation 17 Player (Non-commercial use only)](https://private-user-images.githubusercontent.com/40135721/296934783-f6d1e7ee-e93b-4b39-b09e-69ba004a9b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDIzOTIsIm5iZiI6MTcxMTI0MjA5MiwicGF0aCI6Ii80MDEzNTcyMS8yOTY5MzQ3ODMtZjZkMWU3ZWUtZTkzYi00YjM5LWIwOWUtNjliYTAwNGE5YjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAxMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZjdlYmI3YjMxMDU2YTA5MGMxMDgzMWRmZTYxYmU5Y2E5ODkxZmEzNGY0N2ZiZWRlYWVmOTlmMGQ4YjFhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ntNTNPog_n2OuMP_lormZXNXBrp8yHBE83_zkTLL3Y)

I only tested this tool on a windows machine so if you want it to work in a linux based OS you may have to modify the code yourself.

**Comment by tunay87** [comment]
Getting  error too on Windows machine. Could you please Update it?
